name: wzap
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://bitbucket.org/time-w2o/wzap-flutter-package

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  dio: ^5.3.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
