name: wzap
description: Whatsapp API integration sender for Flutter 
version: 0.0.3
repository: https://github.com/GuilhermeZety/wzap

environment:
  sdk: '>=2.12.0 <4.0.0'

# Add regular dependencies here.
dependencies: 
  dotenv: ^4.2.0
  http: ^1.1.0

dev_dependencies:
  lints: ^2.0.0